### ISSUE TITLE
Named ellipsis match fails

### ISSUE THREAD

**Issue by skrah** [libdynd/libdynd#1116]
As I understand it, both of these should work:

```
>>> ndt.type("... * float64").match(ndt.type("10 * N * float64"))
True
```

```
>>> ndt.type("Dim... * float64").match(ndt.type("10 * N * float64"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dynd/ndt/type.pyx", line 289, in dynd.ndt.type.type.match (/home/stefan/dynd-python/build/temp.linux-x86_64-3.6/dynd/ndt/type.cxx:2982)
TypeError: dim_fragment_type failed to get shape from type 10 * N * float64
>>> 
```

**Comment by mwiebe** [comment]
This is correct. The reason it's broken is the `dim_fragment_type` currently takes a slight shortcut for speed, which is only valid with concrete types. This is to assume the shape is expressible as a sequence of integers, which the dimension variable precludes.

A related question is how in the grammar should we represent a sequence of dimension types without an associated scalar type?

**Comment by skrah** [comment]
Perhaps it is possible to add a dimension_sequence rule to the grammar.  I can try if I get that conflict free. Either that or add a ```nil``` dtype just for the purpose of describing a dtype-less dimension sequence.
