### ISSUE TITLE
Power dimensions should allow whitespace 

### ISSUE THREAD

**Issue by skrah** [libdynd/libdynd#1122]
This is very low priority, but I think power dimensions should allow whitespace:

```
>>> ndt.type("128**10 * float32")
ndt.type('128 * 128 * 128 * 128 * 128 * 128 * 128 * 128 * 128 * 128 * float32')
```

```
>>> ndt.type("128 ** 10 * float32")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dynd/ndt/type.pyx", line 141, in dynd.ndt.type.type.__init__ (/home/stefan/dynd-python/build/temp.linux-x86_64-3.6/dynd/ndt/type.cxx:1550)
  File "dynd/ndt/type.pyx", line 377, in dynd.ndt.type.as_cpp_type (/home/stefan/dynd-python/build/temp.linux-x86_64-3.6/dynd/ndt/type.cxx:4420)
RuntimeError: Error parsing datashape at line 1, column 7
Message: expected a number or a typevar symbol
128 ** 10 * float32
```

**Comment by mwiebe** [comment]
This is also likely easy to fix.
